// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'company_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CompanyModelImpl _$$CompanyModelImplFromJson(Map<String, dynamic> json) =>
    _$CompanyModelImpl(
      EDI: json['EDI'] as String?,
      companyCode: json['companyCode'] as String,
      order: json['order'] as String,
      classification: json['classification'] as String,
      companyNumber: json['companyNumber'] as String?,
      companyChildNumber: json['companyChildNumber'] as String?,
      invoiceNumber: json['invoiceNumber'] as String?,
      kubun: json['kubun'] as String,
      companyName: json['companyName'] as String,
      companyKana: json['companyKana'] as String?,
      companyAbbriviation: json['companyAbbriviation'] as String?,
      kojin: json['kojin'] as String?,
      postalcode: json['postalcode'] as String?,
      postalcodeChild: json['postalcodeChild'] as String?,
      addressA: json['addressA'] as String?,
      addressB: json['addressB'] as String?,
      person: json['person'] as String?,
      phoneNumberA: json['phoneNumberA'] as String?,
      phoneNumberB: json['phoneNumberB'] as String?,
      faxNumber: json['faxNumber'] as String?,
      email: json['email'] as String?,
      URI: json['URI'] as String?,
      responsiblePerson: json['responsiblePerson'] as String?,
      payClass: json['payClass'] as String?,
      closeGroup: json['closeGroup'] as String?,
      paymentConstant: json['paymentConstant'] as String?,
      paymentMethod: json['paymentMethod'] as String?,
      taxMethod: json['taxMethod'] as String?,
      fraction: json['fraction'] as String?,
      accountsPayable: json['accountsPayable'] as String?,
      payeeMemo: json['payeeMemo'] as String?,
      payeeBankCode: json['payeeBankCode'] as String?,
      payeeBankName: json['payeeBankName'] as String?,
      payeeBankBranchCode: json['payeeBankBranchCode'] as String?,
      payeeBankBranchName: json['payeeBankBranchName'] as String?,
      bankAccountType: json['bankAccountType'] as String?,
      bankAccountNumber: json['bankAccountNumber'] as String?,
      bankAcountName: json['bankAcountName'] as String?,
      transferFee: json['transferFee'] as String?,
      calcFee: json['calcFee'] as String?,
      minimumPayPrice: json['minimumPayPrice'] as String?,
      multipleAtOnce: json['multipleAtOnce'] as String?,
      payeeBank: json['payeeBank'] as String?,
      purchasingPattern: json['purchasingPattern'] as String?,
      hidden: json['hidden'] as String?,
      payDayThresholdBefore: json['payDayThresholdBefore'] as String?,
      payDayThresholdAfter: json['payDayThresholdAfter'] as String?,
      payPriceJudge: json['payPriceJudge'] as String?,
      applicable: json['applicable'] as String?,
    );

Map<String, dynamic> _$$CompanyModelImplToJson(_$CompanyModelImpl instance) =>
    <String, dynamic>{
      'EDI': instance.EDI,
      'companyCode': instance.companyCode,
      'order': instance.order,
      'classification': instance.classification,
      'companyNumber': instance.companyNumber,
      'companyChildNumber': instance.companyChildNumber,
      'invoiceNumber': instance.invoiceNumber,
      'kubun': instance.kubun,
      'companyName': instance.companyName,
      'companyKana': instance.companyKana,
      'companyAbbriviation': instance.companyAbbriviation,
      'kojin': instance.kojin,
      'postalcode': instance.postalcode,
      'postalcodeChild': instance.postalcodeChild,
      'addressA': instance.addressA,
      'addressB': instance.addressB,
      'person': instance.person,
      'phoneNumberA': instance.phoneNumberA,
      'phoneNumberB': instance.phoneNumberB,
      'faxNumber': instance.faxNumber,
      'email': instance.email,
      'URI': instance.URI,
      'responsiblePerson': instance.responsiblePerson,
      'payClass': instance.payClass,
      'closeGroup': instance.closeGroup,
      'paymentConstant': instance.paymentConstant,
      'paymentMethod': instance.paymentMethod,
      'taxMethod': instance.taxMethod,
      'fraction': instance.fraction,
      'accountsPayable': instance.accountsPayable,
      'payeeMemo': instance.payeeMemo,
      'payeeBankCode': instance.payeeBankCode,
      'payeeBankName': instance.payeeBankName,
      'payeeBankBranchCode': instance.payeeBankBranchCode,
      'payeeBankBranchName': instance.payeeBankBranchName,
      'bankAccountType': instance.bankAccountType,
      'bankAccountNumber': instance.bankAccountNumber,
      'bankAcountName': instance.bankAcountName,
      'transferFee': instance.transferFee,
      'calcFee': instance.calcFee,
      'minimumPayPrice': instance.minimumPayPrice,
      'multipleAtOnce': instance.multipleAtOnce,
      'payeeBank': instance.payeeBank,
      'purchasingPattern': instance.purchasingPattern,
      'hidden': instance.hidden,
      'payDayThresholdBefore': instance.payDayThresholdBefore,
      'payDayThresholdAfter': instance.payDayThresholdAfter,
      'payPriceJudge': instance.payPriceJudge,
      'applicable': instance.applicable,
    };
