// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'easybiz_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$EasybizModelImpl _$$EasybizModelImplFromJson(Map<String, dynamic> json) =>
    _$EasybizModelImpl(
      skipProcess: json['skipProcess'] as String?,
      purchasingNumber: json['purchasingNumber'] as String?,
      rowNumber: json['rowNumber'] as String?,
      alignmentPattern: json['alignmentPattern'] as String?,
      departmentCode: json['departmentCode'] as String?,
      departmentName: json['departmentName'] as String?,
      personCode: json['personCode'] as String?,
      personName: json['personName'] as String?,
      printOrNot: json['printOrNot'] as String?,
      subjectNumber: json['subjectNumber'] as String?,
      subject: json['subject'] as String?,
      companyCode: json['companyCode'] as String,
      companyName: json['companyName'] as String,
      person: json['person'] as String?,
      closePayingMethod: json['closePayingMethod'] as String?,
      paymentClassification: json['paymentClassification'] as String?,
      paymentMethod: json['paymentMethod'] as String?,
      closeDate: json['closeDate'] as String?,
      paymentSchedule: json['paymentSchedule'] as String?,
      taxRate: json['taxRate'] as String?,
      commentA: json['commentA'] as String?,
      commentB: json['commentB'] as String?,
      commentC: json['commentC'] as String?,
      commentD: json['commentD'] as String?,
      commentE: json['commentE'] as String?,
      commentF: json['commentF'] as String?,
      itemCode: json['itemCode'] as String?,
      itemName: json['itemName'] as String?,
      itemNameChild: json['itemNameChild'] as String?,
      quantity: (json['quantity'] as num?)?.toInt(),
      unit: json['unit'] as String?,
      price: (json['price'] as num?)?.toInt(),
      taxClassification: json['taxClassification'] as String?,
      taxChargeMethod: json['taxChargeMethod'] as String?,
      specialComment: json['specialComment'] as String?,
      stockNumber: json['stockNumber'] as String?,
      stockCode: json['stockCode'] as String?,
      stockQuantity: (json['stockQuantity'] as num?)?.toInt(),
      orderNumber: json['orderNumber'] as String?,
    );

Map<String, dynamic> _$$EasybizModelImplToJson(_$EasybizModelImpl instance) =>
    <String, dynamic>{
      'skipProcess': instance.skipProcess,
      'purchasingNumber': instance.purchasingNumber,
      'rowNumber': instance.rowNumber,
      'alignmentPattern': instance.alignmentPattern,
      'departmentCode': instance.departmentCode,
      'departmentName': instance.departmentName,
      'personCode': instance.personCode,
      'personName': instance.personName,
      'printOrNot': instance.printOrNot,
      'subjectNumber': instance.subjectNumber,
      'subject': instance.subject,
      'companyCode': instance.companyCode,
      'companyName': instance.companyName,
      'person': instance.person,
      'closePayingMethod': instance.closePayingMethod,
      'paymentClassification': instance.paymentClassification,
      'paymentMethod': instance.paymentMethod,
      'closeDate': instance.closeDate,
      'paymentSchedule': instance.paymentSchedule,
      'taxRate': instance.taxRate,
      'commentA': instance.commentA,
      'commentB': instance.commentB,
      'commentC': instance.commentC,
      'commentD': instance.commentD,
      'commentE': instance.commentE,
      'commentF': instance.commentF,
      'itemCode': instance.itemCode,
      'itemName': instance.itemName,
      'itemNameChild': instance.itemNameChild,
      'quantity': instance.quantity,
      'unit': instance.unit,
      'price': instance.price,
      'taxClassification': instance.taxClassification,
      'taxChargeMethod': instance.taxChargeMethod,
      'specialComment': instance.specialComment,
      'stockNumber': instance.stockNumber,
      'stockCode': instance.stockCode,
      'stockQuantity': instance.stockQuantity,
      'orderNumber': instance.orderNumber,
    };
